### ISSUE TITLE
Minimal option currently does not work

### ISSUE THREAD

**Issue by ajstrongdev** [rollingrhinoremix/RRR-builder#31]
Minimal option currently does not remove the GNOME desktop properly, leaving a broken GNOME 42 install with only a few applications rather than a TTY session.

Trying this commit to fix: https://github.com/rollingrhinoremix/RRR-builder/commit/087bd75c2afbb482280c844dff5389c73fa0a937

**Comment by Elsie19** [comment]
I removed the following packages, followed by an `apt autoremove`, and it seemed to fix it:

```bash
ubuntu-desktop-minimal
gnome-shell
```

**Comment by ajstrongdev** [comment]
> I removed the following packages, followed by an `apt autoremove`, and it seemed to fix it:
> 
> ```shell
> ubuntu-desktop-minimal
> gnome-shell
> ```

Can you submit a pull request?

**Comment by cat-master21** [comment]
`gnome-shell` should have been removed but ubuntu-desktop-minimal is not. @Chadano is there an error at the end of trying to install minimal? Something like dpkg breaking.

**Comment by ajstrongdev** [comment]
> `gnome-shell` should have been removed but ubuntu-desktop-minimal is not. @Chadano is there an error at the end of trying to install minimal? Something like dpkg breaking.

Nope, no error

**Comment by ajstrongdev** [comment]
> I removed the following packages, followed by an `apt autoremove`, and it seemed to fix it:
> 
> ```shell
> ubuntu-desktop-minimal
> gnome-shell
> ```

ubuntu-desktop-minimal has been flagged for deletion in #32 - Depending on if it works as intended we can merge the PR

**Comment by ajstrongdev** [comment]
Building the OS failed in #33
